export const BehaviorTypes = {
  TRACK_ELEMENT_USAGE: "TRACK_ELEMENT_USAGE",
  STOP_TRACKING_ELEMENT_USAGE: "STOP_TRACKING_ELEMENT_USAGE",
  EXECUTE: "EXECUTE",
  WINDOW_FOCUS: "WINDOW_FOCUS",
  WINDOW_FOCUS_OUT: "WINDOW_FOCUS_OUT",
  RESET: "RESET",
};
